- name: install and start nginx
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: install nginx
      state: present

    name: start 
  - ansible.builtin.service:
    name: nginx
    state: started